// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    district_health_indicators: {
        name: "district_health_indicators";
        parameters: {
          /** STRING - use sql.string() */
          state_ut: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          district_name: string;
          /** @sqlType STRING */
          state_ut: string;
          /** @sqlType DOUBLE */
          institutional_births_pct: number;
          /** @sqlType DOUBLE */
          improved_water_pct: number;
          /** @sqlType DOUBLE */
          improved_sanitation_pct: number;
          /** @sqlType DOUBLE */
          electricity_pct: number;
          /** @sqlType DOUBLE */
          health_insurance_pct: number;
          /** @sqlType DOUBLE */
          clean_fuel_pct: number;
          /** @sqlType DOUBLE */
          women_literacy_pct: number;
          /** @sqlType DOUBLE */
          family_planning_pct: number;
          /** @sqlType DOUBLE */
          households_surveyed: number;
        }>;
      };
    facilities_by_state: {
        name: "facilities_by_state";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          organization_type: string;
          /** @sqlType BIGINT */
          facility_count: number;
          /** @sqlType BIGINT */
          with_doctors: number;
        }>;
      };
    state_summary: {
        name: "state_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state_ut: string;
          /** @sqlType BIGINT */
          district_count: number;
          /** @sqlType DOUBLE */
          avg_institutional_births_pct: number;
          /** @sqlType DOUBLE */
          avg_improved_water_pct: number;
          /** @sqlType DOUBLE */
          avg_improved_sanitation_pct: number;
          /** @sqlType DOUBLE */
          avg_health_insurance_pct: number;
          /** @sqlType DOUBLE */
          avg_clean_fuel_pct: number;
          /** @sqlType DOUBLE */
          avg_women_literacy_pct: number;
        }>;
      };
  }
}
